language: objective-c
osx_image: xcode7

language: objective-c
osx_image: xcode7.3
xcode_project: OnlyDesignable
xcode_scheme: OnlyDesignable
xcode_sdk: iphonesimulator9.3
env:
  global: 
    - FRAMEWORK_NAME=<THIS_IS_A_PLACEHOLDER_REPLACE_ME>
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap  
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
