language: objective-c
osx_image: xcode7
script:
  - xctool -scheme 'OnlyDesignable' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xctool -scheme 'OnlyDesignable-Sample' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
